name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339712743018:role/arq-oidc-gha
          aws-region: us-east-1

      - name: Debug - List directory contents
        run: ls -R
        working-directory: ./examples/ecs

      - name: Debug - Print Terraform version
        run: terraform version

      - name: Debug - Print AWS CLI version
        run: aws --version

      - name: Initialize Terraform
        run: terraform init -no-color
        working-directory: ./examples/ecs

      - name: Debug - List .terraform directory
        run: ls -R .terraform
        working-directory: ./examples/ecs

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./examples/ecs

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        working-directory: ./examples/ecs
