name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'modules/ecs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/ecs/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339712743018:role/arq-oidc-gha
          aws-region: us-east-1

      - name: Initialize Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform init -backend-config="bucket=arq-terraform-bucket" -backend-config="key=GHA/terraform.tfstate" -backend-config="region=us-east-1"

      - name: Validate Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform validate

      - name: Plan Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform plan -out=plan.tfplan

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./examples/ecs/plan.tfplan

  approve:
    name: Request Approval
    needs: [terraform]
    runs-on: ubuntu-latest

    steps:
      - name: Approval required
        run: echo "Please approve the plan to continue. Once approved, re-run the workflow from the 'Terraform Apply' job."

  apply:
    name: Terraform Apply
    needs: [terraform]
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339712743018:role/arq-oidc-gha
          aws-region: us-east-1

      - name: Download Terraform plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: ./examples/ecs

      - name: Apply Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform apply -auto-approve ./examples/ecs/plan.tfplan
