name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'modules/ecs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/ecs/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339712743018:role/arq-oidc-gha
          aws-region: us-east-1

      - name: Initialize Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform init -backend-config="bucket=arq-terraform-bucket" -backend-config="key=GHA/terraform.tfstate" -backend-config="region=us-east-1"

      - name: Validate Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform validate

      - name: Plan Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform plan -out=plan.tfplan

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ./examples/ecs/plan.tfplan

      - name: Upload lock file
        uses: actions/upload-artifact@v2
        with:
          name: terraform-lock
          path: ./examples/ecs/.terraform.lock.hcl

      - name: Upload .terraform directory
        uses: actions/upload-artifact@v2
        with:
          name: terraform-cache
          path: ./examples/ecs/.terraform

  apply:
    name: Terraform Apply
    needs: [terraform]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/your-repo/actions/runs/

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339712743018:role/arq-oidc-gha
          aws-region: us-east-1

      - name: Download Terraform plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: ./examples/ecs

      - name: Download lock file
        uses: actions/download-artifact@v2
        with:
          name: terraform-lock
          path: ./examples/ecs

      - name: Download .terraform directory
        uses: actions/download-artifact@v2
        with:
          name: terraform-cache
          path: ./examples/ecs/.terraform

      - name: Initialize Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform init -backend-config="bucket=arq-terraform-bucket" -backend-config="key=GHA/terraform.tfstate" -backend-config="region=us-east-1"

      - name: List downloaded files
        run: ls -la ./examples/ecs

      - name: Ensure Terraform providers are executable
        run: chmod -R +x .terraform/providers/

      - name: Apply Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform apply -auto-approve plan.tfplan
