name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Run the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the main branch

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5  # Specify the version of Terraform you are using

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Specify your AWS region

      - name: List root directory contents
        run: ls -la

      - name: List modules directory contents
        run: ls -la ./examples

      - name: List module1 directory contents
        run: ls -la ./examples/ecr

      
      - name: Initialize Terraform for ecr
        working-directory: ./examples/ecr
        run: terraform init

      - name: Validate Terraform for ecr
        working-directory: ./examples/ecr
        run: terraform validate

      - name: Plan Terraform for ecr
        working-directory: ./examples/ecr
        run: terraform plan

      - name: Apply Terraform for ecr
        if: github.ref == 'refs/heads/main'  # Only apply on push to main branch
        working-directory: ./examples/ecr
        run: terraform apply -auto-approve

      - name: Initialize Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform init

      - name: Validate Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform validate

      - name: Plan Terraform for ecs
        working-directory: ./examples/ecs
        run: terraform plan

      - name: Apply Terraform for ecs
        if: github.ref == 'refs/heads/main'  # Only apply on push to main branch
        working-directory: ./examples/ecs
        run: terraform apply -auto-approve
